### PR TITLE
Create move.yml

### PR DESCRIPTION
**Pull request by joewiz**
Enable move bot in main repo

Analogous to https://github.com/eXist-db/exist/pull/1779.

### CODE REVIEW

**Review by lguariento — CHANGES_REQUESTED** [review]
Good stuff - I think these are default settings anyway, right? Perhaps a commented line explaining which are the default values might be helpful (e.g. deleteCommand: true #default: true).

**Comment by joewiz** [comment]
@lguariento I actually copied the settings directly from @duncdrum's PR (https://github.com/eXist-db/exist/pull/1779) that added these to eXist. Duncan, could you advise on Luca's suggestion that we indicate whether we have used only defaults or, if not, where we deviate?

**Comment by duncdrum** [comment]
The link in L1 contains the documentation of the different options, imv that covers our need to document them further. I made some minor adjustments from the default template, we could document them on the gitHub org if folks want that. I don't think this should be a showstopper for this PR though @lguariento.

**Review by duncdrum — APPROVED** [review]

**Review by lguariento — APPROVED** [review]

**Comment by lguariento** [comment]
Sure @duncdrum, agreed!

**Review by dizzzz — APPROVED** [review]

**Comment by joewiz** [comment]
Thanks, guys!

**Pull request merged**
