### PR TITLE
Adopt original dashboard app URL

### PR DESCRIPTION
**Pull request by joewiz**
Now that the new dashboard app is ready to replace the old one in 5.x.x

Closes https://github.com/eXist-db/existdb-dashboard/issues/13.

### CODE REVIEW

**Review by line-o — APPROVED** [review]
I second that approach. It enables a smoother update path and lowers documentation effort.

**Comment by joewiz** [comment]
@line-o Great, thank you. Once this is merged, I can prepare a new release of the app and publish it to the public repo.

**Review by dizzzz — APPROVED** [review]

**Comment by dizzzz** [comment]
I hope the package tooling will remove old code...

**Comment by joewiz** [comment]
@dizzzz Could you be more specific about what your concern is?

**Comment by joewiz** [comment]
@adamretter Thanks!

**Pull request merged**
